# EKS
---

Amazon EKS (Elastic Kubernetes Service) facilita la administración de clústeres de Kubernetes en la nube de AWS. EKS permite ejecutar, gestionar y escalar aplicaciones en contenedores utilizando Kubernetes, sin la necesidad de gestionar manualmente la infraestructura subyacente. Ofrece automatización en la creación y operación de los clústeres, lo que permite que las aplicaciones se mantengan disponibles y optimizadas para cualquier tipo de carga de trabajo.

In [7]:
import json

# Cargar el archivo JSON
file_path_json = 'My Estimate.json'

# Leer el archivo JSON
with open(file_path_json, encoding='latin-1') as f:
    data = json.load(f)

# Buscar el servicio Amazon EKS
for service in data['Grupos']['Servicios']:
    if service['Nombre del servicio'].strip() == 'Amazon EKS':
        eks_service = service
        break

# Imprimir los detalles que tienen información
print("Región:", eks_service['Región'])
print("Costo mensual:", eks_service['Costo del servicio']['mensual'])
print("Costo total (12 meses):", eks_service['Costo del servicio']['12 meses'])



Región: Este de EE. UU. (Ohio)
Costo mensual: 73.00
Costo total (12 meses): 876.00


Amazon EKS fue configurado con clústeres gestionados automáticamente para garantizar la ejecución escalable de contenedores. La cantidad de clústeres se ajusta a las necesidades de la carga de trabajo. La elección de clústeres en EKS proporciona automatización y escalabilidad, optimizando el manejo de los contenedores sin requerir intervención manual.

El costo mensual es de $73.00 USD

El costo total para 12 meses es de $876.00 USD. 

Esta configuración ejecutar y gestiona aplicaciones en contenedores que requieren alta disponibilidad y flexibilidad, minimizando la gestión manual de la infraestructura y asegurando que la escalabilidad sea automática.

## Creación cluster

---

```bash
aws eks create-cluster `
    --name ClusterGrupo4 `
    --region us-east-1 `
    --kubernetes-version 1.30 `
    --role-arn arn:aws:iam::206669603239:role/LabRole `
    --resources-vpc-config subnetIds=subnet-01f1e0bb417953c9b,subnet-07e8ff40b5c55ac5a,securityGroupIds=sg-0c2557b5f8de630dd
```

---

```bash
aws eks create-nodegroup `
    --cluster-name ClusterGrupo4 `
    --nodegroup-name datos1 `
    --scaling-config "minSize=1,maxSize=3,desiredSize=2" `
    --subnets subnet-01f1e0bb417953c9b `
    --instance-types "c5.large" `
    --ami-type "AL2_x86_64" `
    --node-role arn:aws:iam::206669603239:role/LabRole `
    --disk-size 20 `
    --region us-east-1 
```

---

```bash
aws eks create-nodegroup `
    --cluster-name ClusterGrupo4 `
    --nodegroup-name datos2 `
    --scaling-config "minSize=1,maxSize=3,desiredSize=2" `
    --subnets subnet-01f1e0bb417953c9b `
    --instance-types "c5.large" `
    --ami-type "AL2_x86_64" `
    --node-role arn:aws:iam::206669603239:role/LabRole `
    --disk-size 20 `
    --region us-east-1
```

Configuración EKS en AWS

![Configuración EKS en AWS](EKS.JPG)